"""
Path smoothing algorithms for drone navigation.
"""
from typing import List, Optional, Callable
import numpy as np
from scipy.interpolate import splprep, splev
from scipy.optimize import minimize


class PathSmoother:
    """
    Path smoothing utilities for drone navigation.
    
    Provides various methods to smooth paths generated by planners,
    making them more suitable for drone execution.
    """
    
    def __init__(self, collision_checker: Optional[Callable[[np.ndarray], bool]] = None):
        """
        Initialize the path smoother.
        
        Parameters
        ----------
        collision_checker : Optional[Callable[[np.ndarray], bool]]
            Function to check if a position is in collision
        """
        self.collision_checker = collision_checker
    
    def smooth_path(self, path: List[np.ndarray], method: str = "spline", **kwargs) -> List[np.ndarray]:
        """
        Smooth a path using the specified method.
        
        Parameters
        ----------
        path : List[np.ndarray]
            Original path as list of 3D positions
        method : str
            Smoothing method ("spline", "shortcut", "gradient", "bezier")
        **kwargs
            Additional arguments for the smoothing method
            
        Returns
        -------
        List[np.ndarray]
            Smoothed path
        """
        if len(path) < 2:
            return path
        
        if method == "spline":
            return self.spline_smoothing(path, **kwargs)
        elif method == "shortcut":
            return self.shortcut_smoothing(path, **kwargs)
        elif method == "gradient":
            return self.gradient_smoothing(path, **kwargs)
        elif method == "bezier":
            return self.bezier_smoothing(path, **kwargs)
        else:
            raise ValueError(f"Unknown smoothing method: {method}")
    
    def spline_smoothing(self, path: List[np.ndarray], 
                        num_points: int = None,
                        smoothing_factor: float = 0.0,
                        degree: int = 3) -> List[np.ndarray]:
        """
        Smooth path using B-spline interpolation.
        
        Parameters
        ----------
        path : List[np.ndarray]
            Original path
        num_points : int
            Number of points in smoothed path (default: 2x original)
        smoothing_factor : float
            Smoothing factor (0 = interpolation, >0 = approximation)
        degree : int
            Degree of the B-spline
            
        Returns
        -------
        List[np.ndarray]
            Smoothed path
        """
        if len(path) < 2:
            return path
        
        # Convert path to numpy array
        path_array = np.array(path)
        
        # Handle case with too few points for spline
        if len(path) <= degree:
            return self._linear_interpolation(path, num_points or len(path) * 2)
        
        try:
            # Fit B-spline to the path
            tck, u = splprep([path_array[:, 0], path_array[:, 1], path_array[:, 2]], 
                           s=smoothing_factor, k=min(degree, len(path) - 1))
            
            # Generate smoothed path
            if num_points is None:
                num_points = len(path) * 2
            
            u_new = np.linspace(0, 1, num_points)
            smoothed_coords = splev(u_new, tck)
            
            # Convert back to list of arrays
            smoothed_path = [np.array([x, y, z]) for x, y, z in zip(*smoothed_coords)]
            
            # Validate smoothed path for collisions if checker is available
            if self.collision_checker:
                smoothed_path = self._validate_smoothed_path(path, smoothed_path)
            
            return smoothed_path
            
        except Exception as e:
            print(f"Spline smoothing failed: {e}, using linear interpolation")
            return self._linear_interpolation(path, num_points or len(path) * 2)
    
    def shortcut_smoothing(self, path: List[np.ndarray], 
                          max_iterations: int = 100,
                          min_improvement: float = 0.01) -> List[np.ndarray]:
        """
        Smooth path using shortcut method (removing unnecessary waypoints).
        
        Parameters
        ----------
        path : List[np.ndarray]
            Original path
        max_iterations : int
            Maximum number of shortcut attempts
        min_improvement : float
            Minimum path length improvement to continue
            
        Returns
        -------
        List[np.ndarray]
            Smoothed path
        """
        if len(path) < 3:
            return path
        
        smoothed_path = [p.copy() for p in path]
        
        for iteration in range(max_iterations):
            original_length = self._path_length(smoothed_path)
            improved = False
            
            # Try to shortcut between random pairs of waypoints
            for _ in range(len(smoothed_path)):
                if len(smoothed_path) < 3:
                    break
                
                # Choose two random waypoints
                i = np.random.randint(0, len(smoothed_path) - 2)
                j = np.random.randint(i + 2, len(smoothed_path))
                
                # Check if we can connect them directly
                if self._is_path_collision_free(smoothed_path[i], smoothed_path[j]):
                    # Remove intermediate waypoints
                    new_path = smoothed_path[:i+1] + smoothed_path[j:]
                    new_length = self._path_length(new_path)
                    
                    if original_length - new_length > min_improvement:
                        smoothed_path = new_path
                        improved = True
                        break
            
            if not improved:
                break
        
        return smoothed_path
    
    def gradient_smoothing(self, path: List[np.ndarray],
                          iterations: int = 50,
                          step_size: float = 0.1,
                          smoothness_weight: float = 1.0,
                          obstacle_weight: float = 10.0) -> List[np.ndarray]:
        """
        Smooth path using gradient-based optimization.
        
        Parameters
        ----------
        path : List[np.ndarray]
            Original path
        iterations : int
            Number of optimization iterations
        step_size : float
            Gradient descent step size
        smoothness_weight : float
            Weight for smoothness term
        obstacle_weight : float
            Weight for obstacle avoidance term
            
        Returns
        -------
        List[np.ndarray]
            Smoothed path
        """
        if len(path) < 3:
            return path
        
        # Convert to numpy array for easier manipulation
        path_array = np.array(path)
        smoothed_path = path_array.copy()
        
        # Keep start and end points fixed
        for iteration in range(iterations):
            # Calculate gradients for each waypoint (except start and end)
            for i in range(1, len(smoothed_path) - 1):
                gradient = np.zeros(3)
                
                # Smoothness term (minimize curvature)
                prev_point = smoothed_path[i - 1]
                curr_point = smoothed_path[i]
                next_point = smoothed_path[i + 1]
                
                # Second derivative approximation
                curvature = prev_point - 2 * curr_point + next_point
                gradient += smoothness_weight * 2 * curvature
                
                # Obstacle avoidance term
                if self.collision_checker:
                    obstacle_gradient = self._obstacle_gradient(curr_point)
                    gradient += obstacle_weight * obstacle_gradient
                
                # Update position
                smoothed_path[i] -= step_size * gradient
        
        return [p.copy() for p in smoothed_path]
    
    def bezier_smoothing(self, path: List[np.ndarray], 
                        num_points: int = None,
                        control_point_ratio: float = 0.3) -> List[np.ndarray]:
        """
        Smooth path using Bezier curves between waypoints.
        
        Parameters
        ----------
        path : List[np.ndarray]
            Original path
        num_points : int
            Number of points in smoothed path
        control_point_ratio : float
            Ratio for control point placement
            
        Returns
        -------
        List[np.ndarray]
            Smoothed path
        """
        if len(path) < 2:
            return path
        
        if num_points is None:
            num_points = len(path) * 3
        
        smoothed_path = []
        
        for i in range(len(path) - 1):
            start = path[i]
            end = path[i + 1]
            
            # Calculate control points
            if i == 0:
                # First segment
                direction = end - start
                control1 = start + control_point_ratio * direction
                control2 = end - control_point_ratio * direction
            elif i == len(path) - 2:
                # Last segment
                direction = end - start
                control1 = start + control_point_ratio * direction
                control2 = end - control_point_ratio * direction
            else:
                # Middle segments - use previous and next points for smooth transitions
                prev_point = path[i - 1]
                next_point = path[i + 2] if i + 2 < len(path) else path[i + 1]
                
                # Calculate tangent directions
                tangent_start = (end - prev_point) / 2
                tangent_end = (next_point - start) / 2
                
                control1 = start + control_point_ratio * tangent_start
                control2 = end - control_point_ratio * tangent_end
            
            # Generate Bezier curve points
            segment_points = max(2, num_points // (len(path) - 1))
            t_values = np.linspace(0, 1, segment_points)
            
            for t in t_values[:-1]:  # Exclude last point to avoid duplication
                # Cubic Bezier curve formula
                point = (1 - t)**3 * start + \
                       3 * (1 - t)**2 * t * control1 + \
                       3 * (1 - t) * t**2 * control2 + \
                       t**3 * end
                smoothed_path.append(point)
        
        # Add the final point
        smoothed_path.append(path[-1].copy())
        
        return smoothed_path
    
    def _linear_interpolation(self, path: List[np.ndarray], num_points: int) -> List[np.ndarray]:
        """
        Linear interpolation between path points.
        
        Parameters
        ----------
        path : List[np.ndarray]
            Original path
        num_points : int
            Number of points in interpolated path
            
        Returns
        -------
        List[np.ndarray]
            Interpolated path
        """
        if len(path) < 2:
            return path
        
        # Calculate cumulative distances
        distances = [0.0]
        for i in range(1, len(path)):
            dist = np.linalg.norm(path[i] - path[i-1])
            distances.append(distances[-1] + dist)
        
        total_distance = distances[-1]
        if total_distance == 0:
            return path
        
        # Interpolate points
        interpolated_path = []
        for i in range(num_points):
            target_distance = (i / (num_points - 1)) * total_distance
            
            # Find the segment containing this distance
            for j in range(len(distances) - 1):
                if distances[j] <= target_distance <= distances[j + 1]:
                    # Interpolate within this segment
                    segment_ratio = (target_distance - distances[j]) / (distances[j + 1] - distances[j])
                    point = path[j] + segment_ratio * (path[j + 1] - path[j])
                    interpolated_path.append(point)
                    break
        
        return interpolated_path
    
    def _path_length(self, path: List[np.ndarray]) -> float:
        """Calculate total path length."""
        if len(path) < 2:
            return 0.0
        
        total_length = 0.0
        for i in range(1, len(path)):
            total_length += np.linalg.norm(path[i] - path[i-1])
        
        return total_length
    
    def _is_path_collision_free(self, start: np.ndarray, end: np.ndarray, num_checks: int = 10) -> bool:
        """Check if a straight line path is collision-free."""
        if not self.collision_checker:
            return True
        
        for i in range(num_checks + 1):
            t = i / num_checks
            point = start + t * (end - start)
            if self.collision_checker(point):
                return False
        
        return True
    
    def _obstacle_gradient(self, position: np.ndarray, epsilon: float = 0.1) -> np.ndarray:
        """Calculate gradient for obstacle avoidance."""
        if not self.collision_checker:
            return np.zeros(3)
        
        gradient = np.zeros(3)
        
        # Numerical gradient calculation
        for i in range(3):
            pos_plus = position.copy()
            pos_minus = position.copy()
            pos_plus[i] += epsilon
            pos_minus[i] -= epsilon
            
            # Use distance to nearest obstacle as potential field
            cost_plus = 1.0 if self.collision_checker(pos_plus) else 0.0
            cost_minus = 1.0 if self.collision_checker(pos_minus) else 0.0
            
            gradient[i] = (cost_plus - cost_minus) / (2 * epsilon)
        
        return gradient
    
    def _validate_smoothed_path(self, original_path: List[np.ndarray], 
                               smoothed_path: List[np.ndarray]) -> List[np.ndarray]:
        """Validate smoothed path and fallback to original if needed."""
        # Check if smoothed path has collisions
        for point in smoothed_path:
            if self.collision_checker(point):
                print("Smoothed path has collisions, using original path")
                return original_path
        
        # Check if path segments are collision-free
        for i in range(len(smoothed_path) - 1):
            if not self._is_path_collision_free(smoothed_path[i], smoothed_path[i + 1]):
                print("Smoothed path segments have collisions, using original path")
                return original_path
        
        return smoothed_path